### ISSUE TITLE
Write DCAP-specific verification objects

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/attestation#46]
- [x] ~mobilecoinfoundation/attestation#50~ being dropped in favor of #91
- [x] #97 
  - [x] mobilecoinfoundation/sgx#332
  - [x] #96 
- [x] mobilecoinfoundation/attestation#64
- [x] mobilecoinfoundation/attestation#65
- [x] #91
- [x] #98

**Comment by nick-mobilecoin** [comment]
All the basic verifiers are implemented
